version: "3.5"
services:
  websockify:
    image: "statusteam/websockify:v0.10.0"
    command:
      - "80"
      - "nwaku.nwaku.public.dappnode:60000"
  nwaku:
    image: "nwaku.nwaku.public.dappnode.eth:0.1.0"
    build:
      context: nwaku
      args:
        UPSTREAM_VERSION: v0.13.0
    ports:
      - "60000:60000/tcp"
      - "60000:60000/udp"
      - "9005:9005/udp"
    environment:
      DNS_DISCOVERY_URL: >-
        enrtree://AOGECG2SPND25EEFMAJ5WF3KSGJNSGV356DSTL2YVLLZWIV6SAYBM@prod.waku.nodes.status.im
      LOG_LEVEL: DEBUG
      MAX_CONNECTIONS: 150
      STORE_MESSAGE_RETENTION_POLICY: 2592000
      RANDOMIZE_ADDRESS: "true"
      EXTRA_OPTS: ""
    restart: unless-stopped
    volumes:
      - "nwakudb:/data"
volumes:
  nwakudb: {}
